#!/usr/bin/bash

# https://wiki.centos.org/HowTos/Virtualization/VirtualBox

cd /etc/yum.repos.d

wget http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo

yum -y --enablerepo=epel install dkms

yum groupinstall -y "Development Tools"
yum install -y kernel-devel

yum install -y VirtualBox-5.1

