#!/usr/bin/bash

# https://wiki.centos.org/HowTos/Virtualization/VirtualBox

cd /etc/yum.repos.d

wget http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo

yum --enablerepo=epel install dkms

yum groupinstall "Development Tools"
yum install kernel-devel

yum install VirtualBox-5.1

